site_name: "xyz23"
site_description: "abc1111e1e1"
docs_dir: "../../../../../usr/src/app/packages/theme"

nav:
  - Introduction: index.md
  - NAV23: index.md
  - NAV24: index.md

plugins:
  - techdocs-core
